"""empty message

Revision ID: c47245fbcce4
Revises: 683c4fb24f5e
Create Date: 2024-10-07 19:19:21.047439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c47245fbcce4'
down_revision = '683c4fb24f5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites_characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('favorite_character', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['favorite_character'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites_planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('favorite_planet', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['favorite_planet'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('eye_color', sa.String(length=250), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=250),
               existing_nullable=True)
        batch_op.alter_column('birth_year',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=250),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=250),
               nullable=False)

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diameter', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('terrain', sa.String(length=250), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=250),
               existing_nullable=True)
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=250),
               nullable=False)
        batch_op.drop_column('population')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('user_name', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['user_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('user_name')
        batch_op.drop_column('last_name')
        batch_op.drop_column('name')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('population', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('climate',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=25),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('terrain')
        batch_op.drop_column('diameter')

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=25),
               nullable=True)
        batch_op.alter_column('birth_year',
               existing_type=sa.String(length=250),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('eye_color')
        batch_op.drop_column('height')

    op.drop_table('favorites_planets')
    op.drop_table('favorites_characters')
    # ### end Alembic commands ###
